version: '3'

services:
    cremecrm:
        build: .
        container_name: cremecrm
        ports:
            - "8000:8000"
        links:
            - postgres
        volumes:
            - ./docker_settings.py:/webapps/creme_crm/creme/local_settings.py
        environment:
            # Generated when container start, but can be specified
            #- SECRET_KEY=
            - DB_USER=cremeuser
            - DB_PASS=cremepass
            - DB_NAME=cremecrm
            - DB_HOST=postgres
            ## MAILS
            #- EMAIL_SENDER=''
            #- EMAIL_HOST=''
            #- EMAIL_HOST_USER=''
            #- EMAIL_HOST_PASSWORD = ''
            #- EMAIL_USE_TLS=False


    postgres:
      image: postgres:9.5.1
      container_name: cremecrm-db
      expose:
        - 5432
      volumes:
        - ./volumes/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=cremeuser
        - POSTGRES_PASSWORD=cremepass
        - POSTGRES_DB=cremecrm
